services:
  backend:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    volumes:
      - ./FastAPI:/app/FastAPI

    environment:
      SECRET_KEY: "your_super_secret_key_here_please_change_this_to_a_random_string_in_production"
      ALGORITHM: "HS256"
    depends_on:
      - backend_db

    networks:
      - app-network

  frontend:
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      REACT_APP_API_URL: "http://backend:8000"
    depends_on:
      - backend
    networks:
      - app-network

  backend_db:
    image: alpine/git
    volumes:
      - db_data:/app/FastAPI
    command: ["sh", "-c", "echo 'Initializing DB volume...' && sleep 1"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
  backend_node_modules: {}
